django:
  - changed-files:
    - any-glob-to-any-file: ['orders/**', 'pizza/**', 'manage.py']

templates:
  - changed-files:
    - any-glob-to-any-file: 'orders/templates/**'

css:
  - changed-files:
    - any-glob-to-any-file: 'orders/static/**'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

docker:
  - changed-files:
    - any-glob-to-any-file: ['Dockerfile', 'docker-compose.yml']

tests:
  - changed-files:
    - any-glob-to-any-file: 'orders/tests.py'
