# Generated by Django 4.2.16 on 2026-03-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('bowl', 'Bowl'), ('wrap', 'Wrap'), ('salad', 'Salad'), ('smoothie', 'Smoothie'), ('side', 'Side'), ('dessert', 'Dessert')], max_length=20),
        ),
    ]
