# Generated by Django 3.0.6 on 2020-05-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sicilian_Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sicilian_Pizza', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='Large',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='Small',
            field=models.BooleanField(),
        ),
    ]
