# Generated by Django 3.0.6 on 2020-05-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200515_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('Type', models.CharField(max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='regular_pizza',
            old_name='Pizza',
            new_name='Regular_Pizza',
        ),
        migrations.RemoveField(
            model_name='dinner_platters',
            name='Large',
        ),
        migrations.RemoveField(
            model_name='dinner_platters',
            name='Small',
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='Topz',
            field=models.ManyToManyField(blank=True, related_name='Rtopz', to='orders.Toppings'),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='Tops',
            field=models.ManyToManyField(blank=True, related_name='Stopz', to='orders.Toppings'),
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='Tops',
            field=models.ManyToManyField(related_name='Dtopz', to='orders.Toppings'),
        ),
    ]
