# Generated by Django 3.2.4 on 2021-06-19 08:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200516_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='regular_pizza',
            name='Topz',
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='Price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='Price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='Price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='salads',
            name='Price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Toppings',
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='addons2', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='dinner_platters',
            name='Tops',
            field=models.ManyToManyField(related_name='addons0', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='Tops',
            field=models.ManyToManyField(blank=True, related_name='addons1', to='orders.Topping'),
        ),
    ]
