# Generated by Django 3.2.4 on 2021-06-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210619_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_platters',
            name='Tops',
            field=models.ManyToManyField(related_name='DPAddons', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='regular_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='rpAddons', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='Tops',
            field=models.ManyToManyField(blank=True, related_name='spAddons', to='orders.Topping'),
        ),
    ]
