# Generated by Django 3.2.8 on 2021-10-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210619_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner_platters',
            name='slug',
            field=models.SlugField(default=1, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='pasta',
            name='slug',
            field=models.SlugField(default=1, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='regular_pizza',
            name='slug',
            field=models.SlugField(default=1, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='salads',
            name='slug',
            field=models.SlugField(default=1, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='slug',
            field=models.SlugField(default=1, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='subs',
            name='slug',
            field=models.SlugField(default=1, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='topping',
            name='slug',
            field=models.SlugField(default=1, max_length=64, unique=True),
        ),
    ]
