# Generated by Django 3.2.8 on 2021-10-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20211014_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner_platters',
            name='slug',
            field=models.SlugField(default=10, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='pasta',
            name='slug',
            field=models.SlugField(default=9, max_length=64, unique=True),
        ),
    ]
